import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Editor from '@monaco-editor/react';
import { FolderOpen, Play, RotateCcw, Save, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import {
  clearGraphicsCanvas,
  detectGraphicsCode,
  graphicsCanvasSize,
  renderGraphicsProgram,
} from '../src/lib/turboGraphics';

const languages = [
  { label: 'C', value: 'c', monaco: 'c' },
  { label: 'C++', value: 'cpp', monaco: 'cpp' },
  { label: 'Python', value: 'python', monaco: 'python' },
  { label: 'Java', value: 'java', monaco: 'java' },
  { label: 'JavaScript', value: 'javascript', monaco: 'javascript' },
];

const starterCode = {
  c: '#include <stdio.h>\n\nint main() {\n  printf("Hello from BrainBox!\\n");\n  return 0;\n}\n',
  cpp: '#include <iostream>\n\nint main() {\n  std::cout << "Hello from BrainBox!" << std::endl;\n  return 0;\n}\n',
  python: 'print("Hello from BrainBox!")\n',
  java: 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello from BrainBox!");\n  }\n}\n',
  javascript: 'console.log("Hello from BrainBox!");\n',
};

const extensionByLanguage = {
  c: '.c',
  cpp: '.cpp',
  python: '.py',
  java: '.java',
  javascript: '.js',
};

const languageByExtension = {
  '.c': 'c',
  '.cpp': 'cpp',
  '.py': 'python',
  '.java': 'java',
  '.js': 'javascript',
};

function getExtensionFromName(filename = '') {
  const dotIndex = filename.lastIndexOf('.');
  if (dotIndex < 0) {
    return '';
  }
  return filename.slice(dotIndex).toLowerCase();
}

function buildErrorAssistantReport(rawOutput, lang) {
  const text = (rawOutput || '').trim();
  if (!text || !/\[error\]|error|exception|traceback|compilation failed/i.test(text)) {
    return null;
  }

  const lines = text.split('\n').map((line) => line.trim()).filter(Boolean);
  const merged = lines.join(' ');
  const findSourceLine = () => {
    for (const line of lines) {
      let match = line.match(/\bLine\s+(\d+)\b/i);
      if (match) {
        return match[1];
      }

      // Prefer temporary source-file references generated by the compiler runners.
      match = line.match(/\b(?:main\.(?:c|cpp|py|js)|Main\.java):(\d+)(?::\d+)?\b/);
      if (match) {
        return match[1];
      }

      // Python traceback style.
      match = line.match(/\bline\s+(\d+)\b/i);
      if (match && !/node:internal|internal\/modules|node_modules/i.test(line)) {
        return match[1];
      }
    }
    return null;
  };
  const lineNumber = findSourceLine();

  let summary = 'The program failed due to a syntax or runtime issue.';
  const fixes = [];
  const likelyCause = [];

  if (/missing\s*\)|expected\s*\)|unterminated|string literal/i.test(merged)) {
    summary = 'There is an unmatched bracket or unterminated string literal.';
    likelyCause.push('A quote or closing parenthesis is missing near the highlighted expression.');
    fixes.push('Check the nearest `(` `)` and quote pairs and close them properly.');
  }
  if (/cannot find symbol|undefined variable|is not defined/i.test(merged)) {
    summary = 'A variable or symbol is used before declaration/import.';
    likelyCause.push('The identifier in your code does not exist in the current scope.');
    fixes.push('Declare the variable before use, or fix the identifier spelling.');
  }
  if (/syntaxerror|unexpected token|expected expression|compilation failed/i.test(merged)) {
    summary = 'There is a syntax error in your code.';
    likelyCause.push('A token is misplaced or missing in one statement.');
    fixes.push('Inspect the exact failing line and rewrite that statement with minimal syntax.');
  }
  if (/index out of range|nullpointer|segmentation fault|out of bounds/i.test(merged)) {
    summary = 'The program crashed due to invalid memory/index access.';
    likelyCause.push('An array/index/memory access exceeded valid bounds.');
    fixes.push('Validate indices and add boundary checks before access.');
  }

  if (lang === 'java' && /class .* is public, should be declared in a file named/i.test(merged)) {
    summary = 'Java class/file naming mismatch.';
    likelyCause.push('The public class name must match the file name exactly.');
    fixes.push('Use `public class Main` or rename the class to match the saved filename.');
  }

  if (fixes.length === 0) {
    fixes.push('Start from the first error line, fix that one, and run again.');
    fixes.push('If many errors appear, they are often cascading from one earlier syntax issue.');
  }

  return {
    summary,
    lineNumber,
    likelyCause,
    fixes,
  };
}

export default function StartCoding() {
  const [language, setLanguage] = useState('javascript');
  const [codeByLanguage, setCodeByLanguage] = useState(starterCode);
  const [output, setOutput] = useState('Ready. Pick a language and run your program.');
  const [running, setRunning] = useState(false);
  const [showErrorAssistant, setShowErrorAssistant] = useState(false);
  const [outputMode, setOutputMode] = useState('console');
  const canvasRef = useRef(null);
  const runTokenRef = useRef(0);

  const activeLanguage = useMemo(
    () => languages.find((item) => item.value === language) || languages[0],
    [language]
  );

  const estimateInputCount = (lang, code) => {
    if (lang === 'python') {
      return Math.max(1, (code.match(/\binput\s*\(/g) || []).length);
    }
    if (lang === 'c') {
      return Math.max(1, (code.match(/\bscanf\s*\(/g) || []).length);
    }
    if (lang === 'cpp') {
      const cinCount = (code.match(/\bcin\s*>>/g) || []).length;
      return Math.max(1, cinCount);
    }
    if (lang === 'java') {
      const scannerReads = (code.match(/\bnext(?:Int|Long|Double|Float|Line|Short|Byte|Boolean)\s*\(/g) || []).length;
      return Math.max(1, scannerReads);
    }
    if (lang === 'javascript') {
      return 1;
    }
    return 1;
  };

  const codeNeedsInput = (lang, code) => {
    if (lang === 'python') {
      return /\binput\s*\(/.test(code);
    }
    if (lang === 'c') {
      return /\b(scanf|getchar|fgets)\s*\(/.test(code);
    }
    if (lang === 'cpp') {
      return /\b(cin\s*>>|getline\s*\()/.test(code);
    }
    if (lang === 'java') {
      return /\b(Scanner|System\.in|BufferedReader|nextInt|nextLine|nextDouble)\b/.test(code);
    }
    if (lang === 'javascript') {
      return /\bprocess\.stdin\b|\breadFileSync\s*\(\s*0\s*\)/.test(code);
    }
    return false;
  };

  const collectStdIn = (lang, code) => {
    if (!codeNeedsInput(lang, code)) {
      return '';
    }

    const count = Math.min(20, estimateInputCount(lang, code));
    const lines = [];
    for (let i = 0; i < count; i += 1) {
      const value = window.prompt(
        `Input ${i + 1}${count > 1 ? ` of ${count}` : ''} (Cancel to stop adding input):`,
        ''
      );
      if (value === null) {
        break;
      }
      lines.push(value);
    }
    return lines.join('\n');
  };

  const runCode = useCallback(async () => {
    const token = runTokenRef.current + 1;
    runTokenRef.current = token;

    setRunning(true);
    setShowErrorAssistant(false);
    setOutput('Running...');

    try {
      const currentCode = codeByLanguage[language];
      const graphicsRequested = (language === 'c' || language === 'cpp') && detectGraphicsCode(currentCode);

      if (graphicsRequested) {
        const result = await renderGraphicsProgram(
          currentCode,
          canvasRef.current,
          () => runTokenRef.current !== token
        );

        if (runTokenRef.current !== token || result.cancelled) {
          return;
        }

        setOutputMode('graphics');
        setOutput(result.message);
        return;
      }

      setOutputMode('console');
      clearGraphicsCanvas(canvasRef.current, '#000000');

      const stdIn = collectStdIn(language, codeByLanguage[language]);
      const response = await fetch('/api/compile', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          language,
          code: currentCode,
          stdin: stdIn ? `${stdIn}\n` : '',
        }),
      });

      const result = await response.json();
      if (!response.ok) {
        throw new Error(result.error || 'Compilation failed');
      }

      const composed = [
        result.success ? '[ok] Execution completed.' : '[error] Execution failed.',
        result.output ? `\n${result.output}` : '',
        result.error ? `\n${result.error}` : '',
      ]
        .join('')
        .trim();

      setOutput(composed || 'No output');
    } catch (error) {
      setOutput(`[error] ${error.message}`);
    } finally {
      setRunning(false);
    }
  }, [codeByLanguage, language]);

  useEffect(() => {
    clearGraphicsCanvas(canvasRef.current, '#000000');
    return () => {
      runTokenRef.current += 1;
    };
  }, []);

  // Saves editor code to a user-selected local file using File System Access API.
  const saveCodeToFile = useCallback(async (selectedLanguage, code) => {
    try {
      if (!window.showSaveFilePicker) {
        setOutput('[error] Save not supported in this browser. Use Chrome/Edge.');
        return;
      }

      const extension = extensionByLanguage[selectedLanguage] || '.txt';
      const handle = await window.showSaveFilePicker({
        suggestedName: `main${extension}`,
        types: [
          {
            description: `${selectedLanguage} source file`,
            accept: { 'text/plain': [extension] },
          },
        ],
      });

      const writable = await handle.createWritable();
      await writable.write(code);
      await writable.close();
      setOutput('[ok] File saved successfully.');
    } catch (error) {
      if (error?.name === 'AbortError') {
        setOutput('[info] Save cancelled.');
        return;
      }
      setOutput(`[error] Save failed: ${error?.message || 'unknown error'}`);
    }
  }, []);

  // Imports code from a user-selected local file and loads it into editor.
  const importCodeFromFile = useCallback(async () => {
    try {
      if (!window.showOpenFilePicker) {
        setOutput('[error] Import not supported in this browser. Use Chrome/Edge.');
        return;
      }

      const [handle] = await window.showOpenFilePicker({
        multiple: false,
        types: [
          {
            description: 'Source code files',
            accept: {
              'text/plain': ['.c', '.cpp', '.py', '.java', '.js'],
            },
          },
        ],
      });

      const file = await handle.getFile();
      const content = await file.text();
      const ext = getExtensionFromName(file.name);
      const detectedLanguage = languageByExtension[ext] || language;

      setCodeByLanguage((current) => ({
        ...current,
        [detectedLanguage]: content,
      }));
      setLanguage(detectedLanguage);
      setOutput(`[ok] Imported ${file.name}`);
    } catch (error) {
      if (error?.name === 'AbortError') {
        setOutput('[info] Import cancelled.');
        return;
      }
      setOutput(`[error] Import failed: ${error?.message || 'unknown error'}`);
    }
  }, [language]);

  const clearOutput = () => {
    runTokenRef.current += 1;
    setOutput('');
    setShowErrorAssistant(false);
    setOutputMode('console');
    clearGraphicsCanvas(canvasRef.current, '#000000');
  };

  const assistantReport = useMemo(
    () => buildErrorAssistantReport(output, language),
    [language, output]
  );

  useEffect(() => {
    const handleShortcuts = (event) => {
      const key = event.key.toLowerCase();
      if (!(event.ctrlKey || event.metaKey)) {
        return;
      }

      if (key === 's') {
        event.preventDefault();
        void saveCodeToFile(language, codeByLanguage[language]);
      }

      if (key === 'o') {
        event.preventDefault();
        void importCodeFromFile();
      }
    };

    window.addEventListener('keydown', handleShortcuts);
    return () => window.removeEventListener('keydown', handleShortcuts);
  }, [codeByLanguage, importCodeFromFile, language, saveCodeToFile]);

  return (
    <div className="h-screen overflow-hidden bg-[#050912] text-slate-100">
      <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-[#090f1a] px-4 py-3">
        <div className="flex flex-wrap items-center gap-3">
          <Link to="/" className="font-mono text-sm text-slate-300 hover:text-white">
            {'<- Back'}
          </Link>
          <h1 className="font-mono text-lg font-semibold text-white">BrainBox IDE</h1>
          <label className="sr-only" htmlFor="language-select">
            Select language
          </label>
          <select
            id="language-select"
            value={language}
            onChange={(event) => setLanguage(event.target.value)}
            className="rounded-md border border-border bg-[#0f1726] px-3 py-2 text-sm text-slate-100 outline-none focus:border-accent"
          >
            {languages.map((item) => (
              <option key={item.value} value={item.value}>
                {item.label}
              </option>
            ))}
          </select>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={runCode}
            disabled={running}
            className="inline-flex items-center gap-2 rounded-md bg-[#1f6feb] px-3 py-2 text-sm font-semibold text-white transition hover:bg-[#2f7cff] disabled:cursor-not-allowed disabled:opacity-60"
          >
            <Play className="h-4 w-4" />
            Run
          </button>
          <button
            type="button"
            onClick={() => void saveCodeToFile(language, codeByLanguage[language])}
            className="inline-flex items-center gap-2 rounded-md border border-border bg-[#0f1726] px-3 py-2 text-sm font-semibold text-slate-200 transition hover:border-accent"
          >
            <Save className="h-4 w-4" />
            Save Code
          </button>
          <button
            type="button"
            onClick={() => void importCodeFromFile()}
            className="inline-flex items-center gap-2 rounded-md border border-border bg-[#0f1726] px-3 py-2 text-sm font-semibold text-slate-200 transition hover:border-accent"
          >
            <FolderOpen className="h-4 w-4" />
            Import Code
          </button>
          <button
            type="button"
            onClick={clearOutput}
            className="inline-flex items-center gap-2 rounded-md border border-border bg-[#0f1726] px-3 py-2 text-sm font-semibold text-slate-200 transition hover:border-accent"
          >
            <RotateCcw className="h-4 w-4" />
            Clear Output
          </button>
        </div>
      </header>

      <div className="grid h-[calc(100vh-61px)] grid-cols-1 md:grid-cols-[2fr_1fr] overflow-hidden">
        <section className="min-w-0 border-b border-border md:border-b-0 md:border-r">
          <Editor
            height="100%"
            language={activeLanguage.monaco}
            value={codeByLanguage[language]}
            theme="vs-dark"
            onChange={(value) => {
              setCodeByLanguage((current) => ({
                ...current,
                [language]: value || '',
              }));
            }}
            options={{
              minimap: { enabled: false },
              fontFamily: 'JetBrains Mono, Fira Code, monospace',
              fontSize: 14,
              tabSize: 2,
              automaticLayout: true,
              lineNumbers: 'on',
              scrollBeyondLastLine: false,
            }}
          />
        </section>

        <section className="min-w-0 flex flex-col bg-[#060b14]">
          <div className="flex items-center justify-between border-b border-border px-4 py-3">
            <span className="font-mono text-xs uppercase tracking-widest text-slate-400">
              {outputMode === 'graphics' ? 'Output + Canvas' : 'Console'}
            </span>
            <button
              type="button"
              onClick={() => setShowErrorAssistant((current) => !current)}
              disabled={!assistantReport}
              className="inline-flex items-center gap-1 rounded-md border border-border bg-[#0f1726] px-2 py-1 font-mono text-[11px] text-slate-200 transition hover:border-accent disabled:cursor-not-allowed disabled:opacity-50"
            >
              <Sparkles className="h-3.5 w-3.5" />
              Error Assistant
            </button>
          </div>
          {showErrorAssistant && assistantReport && (
            <div className="border-b border-[#5a4d24] bg-[#1b160b] p-3">
              <p className="text-sm font-semibold text-[#f7d387]">{assistantReport.summary}</p>
              {assistantReport.lineNumber && (
                <p className="mt-1 text-xs text-[#e6c47b]">Likely location: line {assistantReport.lineNumber}</p>
              )}
              {assistantReport.likelyCause.length > 0 && (
                <ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-[#f6dc9f]">
                  {assistantReport.likelyCause.map((item, index) => (
                    <li key={`cause-${index}`}>{item}</li>
                  ))}
                </ul>
              )}
              <ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-[#f6dc9f]">
                {assistantReport.fixes.map((item, index) => (
                  <li key={`fix-${index}`}>{item}</li>
                ))}
              </ul>
            </div>
          )}
          {outputMode === 'graphics' && (
            <div className="border-b border-border bg-[#020816] p-3">
              <p className="mb-2 font-mono text-[11px] uppercase tracking-widest text-slate-400">
                Graphics Output
              </p>
              <canvas
                ref={canvasRef}
                width={graphicsCanvasSize.width}
                height={graphicsCanvasSize.height}
                className="block aspect-[640/420] w-full rounded border border-border bg-black"
              />
            </div>
          )}
          <pre className="flex-1 overflow-auto whitespace-pre-wrap break-words p-4 font-mono text-sm text-[#85f4b0]">
            {output}
          </pre>
        </section>
      </div>
    </div>
  );
}
